# Generated by Django 3.1 on 2020-09-01 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demcarac',
            name='restdn',
            field=models.DecimalField(decimal_places=4, max_digits=5, verbose_name='Restdn'),
        ),
        migrations.AlterField(
            model_name='demcarac',
            name='restup',
            field=models.DecimalField(decimal_places=4, max_digits=5, verbose_name='Restup'),
        ),
    ]
