# Generated by Django 3.1 on 2020-09-01 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20200831_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demcarac',
            name='bloque',
            field=models.IntegerField(max_length=3, verbose_name='Bloque'),
        ),
    ]
