# Generated by Django 3.1 on 2020-09-01 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20200901_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demcarac',
            name='bloque',
            field=models.DecimalField(decimal_places=0, max_digits=3, verbose_name='Bloque'),
        ),
    ]
