# Generated by Django 3.1 on 2020-09-08 00:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20200907_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matrizactualdc',
            name='fecha',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Fecha'),
        ),
    ]
