# Generated by Django 3.1 on 2020-09-08 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20200907_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matrizactualdc',
            name='capacidad',
            field=models.DecimalField(decimal_places=5, max_digits=10, verbose_name='Capacidad'),
        ),
        migrations.AlterField(
            model_name='matrizactualdc',
            name='conversion',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True, verbose_name='Conversión'),
        ),
        migrations.AlterField(
            model_name='matrizactualndc',
            name='capacidad',
            field=models.DecimalField(decimal_places=5, max_digits=10, verbose_name='Capacidad'),
        ),
        migrations.AlterField(
            model_name='matrizactualndc',
            name='conversion',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True, verbose_name='Conversión'),
        ),
    ]
