# Generated by Django 3.1 on 2020-09-09 08:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20200907_2000'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demanda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Fecha')),
                ('dia_mes', models.DecimalField(decimal_places=0, max_digits=2, verbose_name='Día mes')),
                ('demanda_energia', models.DecimalField(decimal_places=5, max_digits=10, verbose_name='Demanda energía')),
                ('demanda_energia_dia', models.DecimalField(decimal_places=5, max_digits=10, verbose_name='Demanda energía día')),
            ],
            options={
                'verbose_name': 'Demanda',
                'ordering': ['fecha'],
            },
        ),
    ]
