# Generated by Django 3.1 on 2020-09-14 21:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_demanda'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plantas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agente', models.CharField(max_length=100, verbose_name='Agente')),
                ('planta', models.CharField(max_length=100, verbose_name='Planta')),
                ('tipo', models.CharField(max_length=10, verbose_name='Tipo')),
                ('dc_ndc', models.CharField(max_length=10, verbose_name='DC NDC')),
                ('clasificacion', models.CharField(max_length=10, verbose_name='Clasificación')),
                ('contratos', models.CharField(max_length=10, verbose_name='Contratos')),
                ('enficc_verificada', models.IntegerField(validators=[django.core.validators.MaxLengthValidator(8)], verbose_name='ENFICC verificada')),
                ('enficc_no_comprometida', models.IntegerField(max_length=8, verbose_name='ENFICC no comprometida')),
                ('fecha_inicio_vigencia_enficc', models.DateField(blank=True, null=True, verbose_name='Fecha inicio vigencia ENFICC')),
                ('fecha_fin_vigencia_enficc', models.DateField(blank=True, null=True, verbose_name='Fecha fin vigencia ENFICC')),
                ('combustibles_declarados', models.CharField(blank=True, max_length=100, null=True, verbose_name='Combustibles declarados')),
            ],
            options={
                'verbose_name': 'Plantas',
                'ordering': ['agente'],
            },
        ),
        migrations.AlterModelOptions(
            name='matrizactualdc',
            options={'ordering': ['id'], 'verbose_name': 'MatrizActualDC'},
        ),
        migrations.AlterModelOptions(
            name='matrizactualndc',
            options={'ordering': ['id'], 'verbose_name': 'MatrizActualNDC'},
        ),
        migrations.AlterField(
            model_name='demanda',
            name='fecha',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='matrizactualdc',
            name='fecha',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='matrizactualndc',
            name='fecha',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha'),
        ),
    ]
