# Generated by Django 3.1 on 2020-09-14 21:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_auto_20200914_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantas',
            name='enficc_no_comprometida',
            field=models.IntegerField(validators=[django.core.validators.MaxLengthValidator(8)], verbose_name='ENFICC no comprometida'),
        ),
    ]
