# Generated by Django 3.1 on 2020-09-14 22:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_auto_20200914_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantas',
            name='enficc_no_comprometida',
            field=models.IntegerField(verbose_name='ENFICC no comprometida'),
        ),
        migrations.AlterField(
            model_name='plantas',
            name='enficc_verificada',
            field=models.IntegerField(validators=[django.core.validators.MaxLengthValidator(10)], verbose_name='ENFICC verificada'),
        ),
    ]
