# Generated by Django 3.1 on 2020-09-14 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_auto_20200914_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantas',
            name='enficc_verificada',
            field=models.IntegerField(verbose_name='ENFICC verificada'),
        ),
    ]
