# Generated by Django 3.1 on 2020-09-23 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_auto_20200914_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantas',
            name='contratos',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Contratos'),
        ),
    ]
