# Generated by Django 3.1 on 2020-09-29 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_auto_20200922_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demanda',
            name='demanda_energia_dia',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True, verbose_name='Demanda energía día'),
        ),
    ]
