# Generated by Django 3.0.5 on 2020-10-08 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_adicionales_clp_consolidadoexistente_crecimientomw_cxc_existentescxcclp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demanda',
            name='dia_mes',
            field=models.IntegerField(max_length=2, verbose_name='Día mes'),
        ),
    ]
