# Generated by Django 3.0.5 on 2020-10-09 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_auto_20201008_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cxc',
            name='capacidad',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Capacidad instalada'),
        ),
    ]
