# Generated by Django 3.0.5 on 2020-10-21 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_auto_20201010_2142'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Plantas',
            new_name='Planta',
        ),
    ]
