# Generated by Django 3.0.5 on 2020-10-21 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_auto_20201020_2303'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExistenteCxCCLP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('hidraulica', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Hidraulica')),
                ('liquidos', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Liquidos')),
                ('carbon', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Carbon')),
                ('gas', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Gas')),
                ('glp', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='GLP')),
                ('pch', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='PCH')),
                ('ndc_t', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='NDC_T')),
                ('solar', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Solar')),
                ('eolica', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Eolica')),
                ('existente_cxc_clp', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Existente CxC CLP')),
            ],
            options={
                'verbose_name': 'ExistenteCxCCLP',
                'ordering': ['fecha'],
            },
        ),
        migrations.RenameModel(
            old_name='Adicionales',
            new_name='Adicional',
        ),
        migrations.DeleteModel(
            name='ExistentesCxCCLP',
        ),
        migrations.AlterModelOptions(
            name='adicional',
            options={'ordering': ['fecha'], 'verbose_name': 'Adicional'},
        ),
        migrations.AlterModelOptions(
            name='planta',
            options={'ordering': ['agente'], 'verbose_name': 'Planta'},
        ),
        migrations.RemoveField(
            model_name='planta',
            name='combustibles_declarados',
        ),
        migrations.RemoveField(
            model_name='planta',
            name='contratos',
        ),
        migrations.AddField(
            model_name='planta',
            name='combustible_declarado',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Combustible declarado'),
        ),
        migrations.AddField(
            model_name='planta',
            name='contrato',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Contrato'),
        ),
    ]
