# Generated by Django 3.0.5 on 2020-10-21 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_auto_20201020_2323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cxc',
            name='oef_asignadas',
        ),
        migrations.AddField(
            model_name='cxc',
            name='oef_asignada',
            field=models.IntegerField(blank=True, null=True, verbose_name='OEF asignada'),
        ),
    ]
