# Generated by Django 3.0.5 on 2020-10-30 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0027_auto_20201020_2326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clp',
            name='oef_asignadas',
        ),
        migrations.AddField(
            model_name='clp',
            name='oef_asignada',
            field=models.IntegerField(blank=True, null=True, verbose_name='OEF asignada'),
        ),
    ]
