# Generated by Django 3.0.5 on 2020-11-03 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0028_auto_20201030_1747'),
    ]

    operations = [
        migrations.CreateModel(
            name='CortoPlazo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planta', models.CharField(max_length=100, verbose_name='Planta')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('tipo', models.CharField(max_length=100, verbose_name='Tipo')),
                ('asignacion', models.CharField(max_length=50, verbose_name='Asignación')),
            ],
            options={
                'verbose_name': 'CortoPlazo',
                'ordering': ['tipo'],
            },
        ),
        migrations.CreateModel(
            name='EnergiaFirmeDemanda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicial', models.IntegerField(verbose_name='Fecha inicial')),
                ('fecha_final', models.IntegerField(verbose_name='Fecha final')),
                ('periodicidad_subasta', models.IntegerField(verbose_name='Periodicidad subasta')),
            ],
            options={
                'verbose_name': 'EnergiaFirmeDemanda',
                'ordering': ['fecha_inicial'],
            },
        ),
        migrations.CreateModel(
            name='MetaMatrizERNC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.IntegerField(verbose_name='Fecha')),
                ('eolica', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Eolica')),
                ('solar', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Solar')),
                ('pch', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='PCH')),
                ('ndc_t', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='NDC_T')),
                ('ernc', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='ERNC')),
            ],
            options={
                'verbose_name': 'MetaMatrizERNC',
                'ordering': ['fecha'],
            },
        ),
    ]
