# Generated by Django 3.0.5 on 2020-11-09 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0029_cortoplazo_energiafirmedemanda_metamatrizernc'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapacidadAdicionalMaxERNC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.IntegerField(verbose_name='Fecha')),
                ('eolica', models.IntegerField(blank=True, null=True, verbose_name='Eolica')),
                ('solar', models.IntegerField(blank=True, null=True, verbose_name='Solar')),
                ('pch', models.IntegerField(blank=True, null=True, verbose_name='PCH')),
                ('ndc_t', models.IntegerField(blank=True, null=True, verbose_name='NDC_T')),
                ('ernc', models.IntegerField(blank=True, null=True, verbose_name='ERNC')),
            ],
            options={
                'verbose_name': 'CapacidadAdicionalMaxERNC',
                'ordering': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='MetaMatriz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.IntegerField(verbose_name='Fecha')),
                ('liquidos', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Liquidos')),
                ('carbon', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Carbon')),
                ('gas', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Gas')),
                ('glp', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='GLP')),
                ('hidraulica', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Hidráulica')),
            ],
            options={
                'verbose_name': 'MetaMatriz',
                'ordering': ['fecha'],
            },
        ),
    ]
