# Generated by Django 3.0.5 on 2020-11-11 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0030_capacidadadicionalmaxernc_metamatriz'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapacidadAdicionalMax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.IntegerField(verbose_name='Fecha')),
                ('liquidos', models.IntegerField(blank=True, null=True, verbose_name='Liquidos')),
                ('carbon', models.IntegerField(blank=True, null=True, verbose_name='Carbon')),
                ('gas', models.IntegerField(blank=True, null=True, verbose_name='Gas')),
                ('glp', models.IntegerField(blank=True, null=True, verbose_name='GLP')),
                ('hidraulica', models.IntegerField(blank=True, null=True, verbose_name='Hidráulica')),
            ],
            options={
                'verbose_name': 'CapacidadAdicionalMax',
                'ordering': ['fecha'],
            },
        ),
    ]
