# Generated by Django 3.0.5 on 2020-11-12 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0031_capacidadadicionalmax'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CapacidadAdicionalMax',
            new_name='PlanCapacidadAdicionalMax',
        ),
        migrations.RenameModel(
            old_name='CapacidadAdicionalMaxERNC',
            new_name='PlanCapacidadAdicionalMaxERNC',
        ),
        migrations.RenameModel(
            old_name='CortoPlazo',
            new_name='PlanCortoPlazo',
        ),
        migrations.RenameModel(
            old_name='EnergiaFirmeDemanda',
            new_name='PlanEnergiaFirmeDemanda',
        ),
        migrations.RenameModel(
            old_name='MetaMatriz',
            new_name='PlanMetaMatriz',
        ),
        migrations.RenameModel(
            old_name='MetaMatrizERNC',
            new_name='PlanMetaMatrizERNC',
        ),
        migrations.AlterModelOptions(
            name='plancapacidadadicionalmax',
            options={'ordering': ['fecha'], 'verbose_name': 'PlanCapacidadAdicionalMax'},
        ),
        migrations.AlterModelOptions(
            name='plancapacidadadicionalmaxernc',
            options={'ordering': ['fecha'], 'verbose_name': 'PlanCapacidadAdicionalMaxERNC'},
        ),
        migrations.AlterModelOptions(
            name='plancortoplazo',
            options={'ordering': ['planta'], 'verbose_name': 'PlanCortoPlazo'},
        ),
        migrations.AlterModelOptions(
            name='planenergiafirmedemanda',
            options={'ordering': ['fecha_inicial'], 'verbose_name': 'PlanEnergiaFirmeDemanda'},
        ),
        migrations.AlterModelOptions(
            name='planmetamatriz',
            options={'ordering': ['fecha'], 'verbose_name': 'PlanMetaMatriz'},
        ),
        migrations.AlterModelOptions(
            name='planmetamatrizernc',
            options={'ordering': ['fecha'], 'verbose_name': 'PlanMetaMatrizERNC'},
        ),
    ]
