# Generated by Django 3.0.5 on 2020-11-13 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0032_auto_20201112_1716'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapMax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.IntegerField(verbose_name='Fecha')),
                ('hidraulica', models.IntegerField(verbose_name='Hidráulica')),
                ('liquidos', models.IntegerField(verbose_name='Liquidos')),
                ('carbon', models.IntegerField(verbose_name='Carbon')),
                ('gas', models.IntegerField(verbose_name='Gas')),
                ('glp', models.IntegerField(verbose_name='GLP')),
                ('pch', models.IntegerField(verbose_name='PCH')),
                ('ndc_t', models.IntegerField(verbose_name='NDC_T')),
                ('solar', models.IntegerField(verbose_name='Solar')),
                ('eolica', models.IntegerField(verbose_name='Eolica')),
            ],
            options={
                'verbose_name': 'CapMax',
                'ordering': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='DemENFICCFil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('demanda_energia', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Demanda energía')),
                ('enficc', models.DecimalField(decimal_places=5, max_digits=10, verbose_name='ENFICC')),
            ],
            options={
                'verbose_name': 'DemENFICCFil',
                'ordering': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='DEntradaTec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable', models.CharField(max_length=100, verbose_name='Variable')),
                ('hidraulica', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Hidráulica')),
                ('liquidos', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Liquidos')),
                ('carbon', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Carbon')),
                ('gas', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Gas')),
                ('glp', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='GLP')),
                ('pch', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='PCH')),
                ('ndc_t', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='NDC_T')),
                ('solar', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Solar')),
                ('eolica', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Eolica')),
            ],
            options={
                'verbose_name': 'DEntradaTec',
                'ordering': ['variable'],
            },
        ),
        migrations.CreateModel(
            name='LCOE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.IntegerField(verbose_name='Fecha')),
                ('hidraulica', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Hidráulica')),
                ('liquidos', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Liquidos')),
                ('carbon', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Carbon')),
                ('gas', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Gas')),
                ('glp', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='GLP')),
                ('pch', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='PCH')),
                ('ndc_t', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='NDC_T')),
                ('solar', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Solar')),
                ('eolica', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Eolica')),
            ],
            options={
                'verbose_name': 'LCOE',
                'ordering': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='MetaMatriz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.IntegerField(verbose_name='Fecha')),
                ('hidraulica', models.DecimalField(decimal_places=4, max_digits=6, verbose_name='Hidráulica')),
                ('liquidos', models.DecimalField(decimal_places=4, max_digits=6, verbose_name='Liquidos')),
                ('carbon', models.DecimalField(decimal_places=4, max_digits=6, verbose_name='Carbon')),
                ('gas', models.DecimalField(decimal_places=4, max_digits=6, verbose_name='Gas')),
                ('glp', models.DecimalField(decimal_places=4, max_digits=6, verbose_name='GLP')),
                ('pch', models.DecimalField(decimal_places=4, max_digits=6, verbose_name='PCH')),
                ('ndc_t', models.DecimalField(decimal_places=4, max_digits=6, verbose_name='NDC_T')),
                ('solar', models.DecimalField(decimal_places=4, max_digits=6, verbose_name='Solar')),
                ('eolica', models.DecimalField(decimal_places=4, max_digits=6, verbose_name='Eolica')),
            ],
            options={
                'verbose_name': 'MetaMatriz',
                'ordering': ['fecha'],
            },
        ),
        migrations.AlterField(
            model_name='adicional',
            name='hidraulica',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Hidráulica'),
        ),
        migrations.AlterField(
            model_name='crecimientomw',
            name='hidraulica',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Hidráulica'),
        ),
        migrations.AlterField(
            model_name='existentecxcclp',
            name='hidraulica',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Hidráulica'),
        ),
    ]
