# Generated by Django 3.0.5 on 2020-11-19 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0033_auto_20201112_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cxc',
            name='fecha_entrada',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha entrada'),
        ),
    ]
