# Generated by Django 3.0.5 on 2020-11-19 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0034_auto_20201118_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clp',
            name='fecha_entrada',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha entrada'),
        ),
    ]
