# Generated by Django 3.0.5 on 2020-12-15 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0036_auto_20201119_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capmax',
            name='carbon',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Carbon'),
        ),
        migrations.AlterField(
            model_name='capmax',
            name='eolica',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Eolica'),
        ),
        migrations.AlterField(
            model_name='capmax',
            name='gas',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Gas'),
        ),
        migrations.AlterField(
            model_name='capmax',
            name='glp',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='GLP'),
        ),
        migrations.AlterField(
            model_name='capmax',
            name='hidraulica',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Hidráulica'),
        ),
        migrations.AlterField(
            model_name='capmax',
            name='liquidos',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Liquidos'),
        ),
        migrations.AlterField(
            model_name='capmax',
            name='ndc_t',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='NDC_T'),
        ),
        migrations.AlterField(
            model_name='capmax',
            name='pch',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='PCH'),
        ),
        migrations.AlterField(
            model_name='capmax',
            name='solar',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Solar'),
        ),
        migrations.AlterField(
            model_name='consolidadoexistente',
            name='capacidad',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Capacidad'),
        ),
        migrations.AlterField(
            model_name='cxc',
            name='oef_asignada',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='OEF asignada'),
        ),
        migrations.AlterField(
            model_name='plancapacidadadicionalmax',
            name='carbon',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Carbon'),
        ),
        migrations.AlterField(
            model_name='plancapacidadadicionalmax',
            name='gas',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Gas'),
        ),
        migrations.AlterField(
            model_name='plancapacidadadicionalmax',
            name='glp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='GLP'),
        ),
        migrations.AlterField(
            model_name='plancapacidadadicionalmax',
            name='hidraulica',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Hidráulica'),
        ),
        migrations.AlterField(
            model_name='plancapacidadadicionalmax',
            name='liquidos',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Liquidos'),
        ),
        migrations.AlterField(
            model_name='plancapacidadadicionalmaxernc',
            name='eolica',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Eolica'),
        ),
        migrations.AlterField(
            model_name='plancapacidadadicionalmaxernc',
            name='ernc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='ERNC'),
        ),
        migrations.AlterField(
            model_name='plancapacidadadicionalmaxernc',
            name='ndc_t',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='NDC_T'),
        ),
        migrations.AlterField(
            model_name='plancapacidadadicionalmaxernc',
            name='pch',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='PCH'),
        ),
        migrations.AlterField(
            model_name='plancapacidadadicionalmaxernc',
            name='solar',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Solar'),
        ),
        migrations.AlterField(
            model_name='planta',
            name='enficc_no_comprometida',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='ENFICC no comprometida'),
        ),
        migrations.AlterField(
            model_name='planta',
            name='enficc_verificada',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='ENFICC verificada'),
        ),
    ]
