# Generated by Django 3.0.5 on 2020-12-21 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0037_auto_20201215_1757'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegresionMetaMatriz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.IntegerField(verbose_name='Fecha')),
                ('eolica', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Eolica')),
                ('solar', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Solar')),
                ('pch', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='PCH')),
                ('ndc_t', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='NDC_T')),
                ('ernc', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='ERNC')),
                ('liquidos', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Liquidos')),
                ('carbon', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Carbon')),
                ('gas', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Gas')),
                ('glp', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='GLP')),
                ('termica', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='PCH')),
                ('hidraulica', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Hidráulica')),
            ],
            options={
                'verbose_name': 'RegresionMetaMatriz',
                'ordering': ['fecha'],
            },
        ),
    ]
